# Шрифти
font_family      JetBrainsMono Nerd Font
font_size        11.0

# Прозорість і Блюр
background_opacity 0.1
confirm_os_window_close 0

# Кольори
include theme.conf

# Відступи (щоб текст не прилипав до країв)
window_padding_width 10

# Курсор (зробимо його "дихаючим")
cursor_shape beam
cursor_beam_thickness 1.5

shell fish

include ~/.cache/wal/colors-kitty.conf

# Ставимо прозорість фону (0.5 - це 50% прозорості)
# Це вплине ТІЛЬКИ на фон, текст залишиться на 100% чітким!
background_opacity 0.1	

# Щоб фон був темнішим за шпалери (ефект тонування), 
# переконайся, що колір фону чорний:
background #000000
dynamic_background_opacity no
